from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import ForeignKey, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Log(Base):
    __tablename__ = "logs"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc))
    endpoint: Mapped[str] = mapped_column(String, nullable=False)
    method: Mapped[str] = mapped_column(String, nullable=False)
    status_code: Mapped[int] = mapped_column(nullable=False)
    response_time_ms: Mapped[float] = mapped_column(nullable=False)
    error: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    prediction_id: Mapped[Optional[int]] = mapped_column(ForeignKey("predictions.id"), nullable=True)
    prediction: Mapped[Optional["Prediction"]] = relationship("Prediction", back_populates="log")


class Prediction(Base):
    __tablename__ = "predictions"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc))
    log: Mapped[Optional["Log"]] = relationship("Log", back_populates="prediction", uselist=False)

    # Prédiction
    score: Mapped[float] = mapped_column(nullable=False)
    decision: Mapped[str] = mapped_column(String, nullable=False)
    inference_time_ms: Mapped[float] = mapped_column(nullable=False)

    # Features obligatoires
    DAYS_BIRTH: Mapped[float] = mapped_column(nullable=False)
    DAYS_EMPLOYED: Mapped[float] = mapped_column(nullable=False)
    AMT_INCOME_TOTAL: Mapped[float] = mapped_column(nullable=False)
    AMT_CREDIT: Mapped[float] = mapped_column(nullable=False)
    AMT_ANNUITY: Mapped[float] = mapped_column(nullable=False)

    # Profil client
    CODE_GENDER: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    CNT_CHILDREN: Mapped[Optional[int]] = mapped_column(nullable=True)
    CNT_FAM_MEMBERS: Mapped[Optional[float]] = mapped_column(nullable=True)
    NAME_CONTRACT_TYPE: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    NAME_FAMILY_STATUS: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    NAME_HOUSING_TYPE: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    NAME_INCOME_TYPE: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    NAME_EDUCATION_TYPE: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    NAME_TYPE_SUITE: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    OCCUPATION_TYPE: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    ORGANIZATION_TYPE: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    FLAG_OWN_CAR: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    FLAG_OWN_REALTY: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    AMT_GOODS_PRICE: Mapped[Optional[float]] = mapped_column(nullable=True)
    DAYS_REGISTRATION: Mapped[Optional[float]] = mapped_column(nullable=True)
    DAYS_ID_PUBLISH: Mapped[Optional[float]] = mapped_column(nullable=True)
    DAYS_LAST_PHONE_CHANGE: Mapped[Optional[float]] = mapped_column(nullable=True)
    DAYS_EMPLOYED_ANOM: Mapped[Optional[bool]] = mapped_column(nullable=True)
    HOUR_APPR_PROCESS_START: Mapped[Optional[int]] = mapped_column(nullable=True)
    WEEKDAY_APPR_PROCESS_START: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    EXT_SOURCE_1: Mapped[Optional[float]] = mapped_column(nullable=True)
    EXT_SOURCE_2: Mapped[Optional[float]] = mapped_column(nullable=True)
    EXT_SOURCE_3: Mapped[Optional[float]] = mapped_column(nullable=True)
    REGION_POPULATION_RELATIVE: Mapped[Optional[float]] = mapped_column(nullable=True)
    REGION_RATING_CLIENT: Mapped[Optional[int]] = mapped_column(nullable=True)
    REGION_RATING_CLIENT_W_CITY: Mapped[Optional[int]] = mapped_column(nullable=True)
    REG_REGION_NOT_LIVE_REGION: Mapped[Optional[int]] = mapped_column(nullable=True)
    REG_REGION_NOT_WORK_REGION: Mapped[Optional[int]] = mapped_column(nullable=True)
    REG_CITY_NOT_LIVE_CITY: Mapped[Optional[int]] = mapped_column(nullable=True)
    REG_CITY_NOT_WORK_CITY: Mapped[Optional[int]] = mapped_column(nullable=True)
    LIVE_REGION_NOT_WORK_REGION: Mapped[Optional[int]] = mapped_column(nullable=True)
    LIVE_CITY_NOT_WORK_CITY: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLOORSMAX_AVG: Mapped[Optional[float]] = mapped_column(nullable=True)
    FLOORSMAX_MODE: Mapped[Optional[float]] = mapped_column(nullable=True)
    FLOORSMAX_MEDI: Mapped[Optional[float]] = mapped_column(nullable=True)
    TOTALAREA_MODE: Mapped[Optional[float]] = mapped_column(nullable=True)
    YEARS_BEGINEXPLUATATION_AVG: Mapped[Optional[float]] = mapped_column(nullable=True)
    YEARS_BEGINEXPLUATATION_MODE: Mapped[Optional[float]] = mapped_column(nullable=True)
    YEARS_BEGINEXPLUATATION_MEDI: Mapped[Optional[float]] = mapped_column(nullable=True)
    EMERGENCYSTATE_MODE: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    FLAG_MOBIL: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_EMP_PHONE: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_WORK_PHONE: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_CONT_MOBILE: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_PHONE: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_EMAIL: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_2: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_3: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_4: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_5: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_6: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_7: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_8: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_9: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_10: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_11: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_12: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_13: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_14: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_15: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_16: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_17: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_18: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_19: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_20: Mapped[Optional[int]] = mapped_column(nullable=True)
    FLAG_DOCUMENT_21: Mapped[Optional[int]] = mapped_column(nullable=True)
    OBS_30_CNT_SOCIAL_CIRCLE: Mapped[Optional[float]] = mapped_column(nullable=True)
    DEF_30_CNT_SOCIAL_CIRCLE: Mapped[Optional[float]] = mapped_column(nullable=True)
    OBS_60_CNT_SOCIAL_CIRCLE: Mapped[Optional[float]] = mapped_column(nullable=True)
    DEF_60_CNT_SOCIAL_CIRCLE: Mapped[Optional[float]] = mapped_column(nullable=True)
    AMT_REQ_CREDIT_BUREAU_HOUR: Mapped[Optional[float]] = mapped_column(nullable=True)
    AMT_REQ_CREDIT_BUREAU_DAY: Mapped[Optional[float]] = mapped_column(nullable=True)
    AMT_REQ_CREDIT_BUREAU_WEEK: Mapped[Optional[float]] = mapped_column(nullable=True)
    AMT_REQ_CREDIT_BUREAU_MON: Mapped[Optional[float]] = mapped_column(nullable=True)
    AMT_REQ_CREDIT_BUREAU_QRT: Mapped[Optional[float]] = mapped_column(nullable=True)
    AMT_REQ_CREDIT_BUREAU_YEAR: Mapped[Optional[float]] = mapped_column(nullable=True)
    bureau_count: Mapped[Optional[float]] = mapped_column(nullable=True)
    bureau_active_count: Mapped[Optional[float]] = mapped_column(nullable=True)
    actif_count: Mapped[Optional[float]] = mapped_column(nullable=True)
    cloture_count: Mapped[Optional[float]] = mapped_column(nullable=True)
    bureau_overdue_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    bureau_debt_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    actif_debt_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    cloture_debt_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    prev_count: Mapped[Optional[float]] = mapped_column(nullable=True)
    approve_count: Mapped[Optional[float]] = mapped_column(nullable=True)
    refuse_count: Mapped[Optional[float]] = mapped_column(nullable=True)
    prev_refused_count: Mapped[Optional[float]] = mapped_column(nullable=True)
    taux_refus: Mapped[Optional[float]] = mapped_column(nullable=True)
    prev_credit_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    approve_credit_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    refuse_credit_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    a_carte_credit: Mapped[Optional[float]] = mapped_column(nullable=True)
    cc_balance_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    cc_dpd_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    cc_utilisation_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    pos_dpd_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    pos_dpd_max: Mapped[Optional[float]] = mapped_column(nullable=True)
    inst_retard_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    inst_retard_max: Mapped[Optional[float]] = mapped_column(nullable=True)
    inst_diff_mean: Mapped[Optional[float]] = mapped_column(nullable=True)
    a_eu_retard: Mapped[Optional[float]] = mapped_column(nullable=True)
