from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    pass


class Log(Base):
    __tablename__ = "logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    endpoint = Column(String, nullable=False)
    method = Column(String, nullable=False)
    status_code = Column(Integer, nullable=False)
    response_time_ms = Column(Float, nullable=False)
    error = Column(String)
    prediction_id = Column(Integer, ForeignKey("predictions.id"), nullable=True)
    prediction = relationship("Prediction", back_populates="log")


class Prediction(Base):
    __tablename__ = "predictions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    log = relationship("Log", back_populates="prediction", uselist=False)

    # Prédiction
    score = Column(Float, nullable=False)
    decision = Column(String, nullable=False)
    inference_time_ms = Column(Float, nullable=False)

    # Features obligatoires
    DAYS_BIRTH = Column(Float, nullable=False)
    DAYS_EMPLOYED = Column(Float, nullable=False)
    AMT_INCOME_TOTAL = Column(Float, nullable=False)
    AMT_CREDIT = Column(Float, nullable=False)
    AMT_ANNUITY = Column(Float, nullable=False)

    # Profil client
    CODE_GENDER = Column(String)
    CNT_CHILDREN = Column(Integer)
    CNT_FAM_MEMBERS = Column(Float)
    NAME_CONTRACT_TYPE = Column(String)
    NAME_FAMILY_STATUS = Column(String)
    NAME_HOUSING_TYPE = Column(String)
    NAME_INCOME_TYPE = Column(String)
    NAME_EDUCATION_TYPE = Column(String)
    NAME_TYPE_SUITE = Column(String)
    OCCUPATION_TYPE = Column(String)
    ORGANIZATION_TYPE = Column(String)
    FLAG_OWN_CAR = Column(String)
    FLAG_OWN_REALTY = Column(String)
    AMT_GOODS_PRICE = Column(Float)
    DAYS_REGISTRATION = Column(Float)
    DAYS_ID_PUBLISH = Column(Float)
    DAYS_LAST_PHONE_CHANGE = Column(Float)
    DAYS_EMPLOYED_ANOM = Column(Boolean)
    HOUR_APPR_PROCESS_START = Column(Integer)
    WEEKDAY_APPR_PROCESS_START = Column(String)
    EXT_SOURCE_1 = Column(Float)
    EXT_SOURCE_2 = Column(Float)
    EXT_SOURCE_3 = Column(Float)
    REGION_POPULATION_RELATIVE = Column(Float)
    REGION_RATING_CLIENT = Column(Integer)
    REGION_RATING_CLIENT_W_CITY = Column(Integer)
    REG_REGION_NOT_LIVE_REGION = Column(Integer)
    REG_REGION_NOT_WORK_REGION = Column(Integer)
    REG_CITY_NOT_LIVE_CITY = Column(Integer)
    REG_CITY_NOT_WORK_CITY = Column(Integer)
    LIVE_REGION_NOT_WORK_REGION = Column(Integer)
    LIVE_CITY_NOT_WORK_CITY = Column(Integer)
    FLOORSMAX_AVG = Column(Float)
    FLOORSMAX_MODE = Column(Float)
    FLOORSMAX_MEDI = Column(Float)
    TOTALAREA_MODE = Column(Float)
    YEARS_BEGINEXPLUATATION_AVG = Column(Float)
    YEARS_BEGINEXPLUATATION_MODE = Column(Float)
    YEARS_BEGINEXPLUATATION_MEDI = Column(Float)
    EMERGENCYSTATE_MODE = Column(String)
    FLAG_MOBIL = Column(Integer)
    FLAG_EMP_PHONE = Column(Integer)
    FLAG_WORK_PHONE = Column(Integer)
    FLAG_CONT_MOBILE = Column(Integer)
    FLAG_PHONE = Column(Integer)
    FLAG_EMAIL = Column(Integer)
    FLAG_DOCUMENT_2 = Column(Integer)
    FLAG_DOCUMENT_3 = Column(Integer)
    FLAG_DOCUMENT_4 = Column(Integer)
    FLAG_DOCUMENT_5 = Column(Integer)
    FLAG_DOCUMENT_6 = Column(Integer)
    FLAG_DOCUMENT_7 = Column(Integer)
    FLAG_DOCUMENT_8 = Column(Integer)
    FLAG_DOCUMENT_9 = Column(Integer)
    FLAG_DOCUMENT_10 = Column(Integer)
    FLAG_DOCUMENT_11 = Column(Integer)
    FLAG_DOCUMENT_12 = Column(Integer)
    FLAG_DOCUMENT_13 = Column(Integer)
    FLAG_DOCUMENT_14 = Column(Integer)
    FLAG_DOCUMENT_15 = Column(Integer)
    FLAG_DOCUMENT_16 = Column(Integer)
    FLAG_DOCUMENT_17 = Column(Integer)
    FLAG_DOCUMENT_18 = Column(Integer)
    FLAG_DOCUMENT_19 = Column(Integer)
    FLAG_DOCUMENT_20 = Column(Integer)
    FLAG_DOCUMENT_21 = Column(Integer)
    OBS_30_CNT_SOCIAL_CIRCLE = Column(Float)
    DEF_30_CNT_SOCIAL_CIRCLE = Column(Float)
    OBS_60_CNT_SOCIAL_CIRCLE = Column(Float)
    DEF_60_CNT_SOCIAL_CIRCLE = Column(Float)
    AMT_REQ_CREDIT_BUREAU_HOUR = Column(Float)
    AMT_REQ_CREDIT_BUREAU_DAY = Column(Float)
    AMT_REQ_CREDIT_BUREAU_WEEK = Column(Float)
    AMT_REQ_CREDIT_BUREAU_MON = Column(Float)
    AMT_REQ_CREDIT_BUREAU_QRT = Column(Float)
    AMT_REQ_CREDIT_BUREAU_YEAR = Column(Float)
    bureau_count = Column(Float)
    bureau_active_count = Column(Float)
    actif_count = Column(Float)
    cloture_count = Column(Float)
    bureau_overdue_mean = Column(Float)
    bureau_debt_mean = Column(Float)
    actif_debt_mean = Column(Float)
    cloture_debt_mean = Column(Float)
    prev_count = Column(Float)
    approve_count = Column(Float)
    refuse_count = Column(Float)
    prev_refused_count = Column(Float)
    taux_refus = Column(Float)
    prev_credit_mean = Column(Float)
    approve_credit_mean = Column(Float)
    refuse_credit_mean = Column(Float)
    a_carte_credit = Column(Float)
    cc_balance_mean = Column(Float)
    cc_dpd_mean = Column(Float)
    cc_utilisation_mean = Column(Float)
    pos_dpd_mean = Column(Float)
    pos_dpd_max = Column(Float)
    inst_retard_mean = Column(Float)
    inst_retard_max = Column(Float)
    inst_diff_mean = Column(Float)
    a_eu_retard = Column(Float)
